### ISSUE TITLE
video has no sound

### ISSUE THREAD

**Issue by mutzl** [Djohnnie/MyHome-DotNetConf-2020#1]
just wanted to let you know, that the video https://www.youtube.com/watch?v=1WscRcEyb0Y of your talk has sound only for the first 6 minutes.

**Comment by Djohnnie** [comment]
I've asked the people that did the recordings to fix this. Hopefully, they are able to do that.

**Comment by Djohnnie** [comment]
Audio has been fixed, and the video was re-uploaded: [https://www.youtube.com/watch?v=SGSBZhbIX2E](https://www.youtube.com/watch?v=SGSBZhbIX2E)
